title: Hello, world! I'm Vital Cadlec Akpamoli
description: Software Engineer and web developer enthusiast
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Vital Cadlec S. AKPAMOLI # add your name
author-img: vital-Akpamoli.jpg # add your photo
about-author: I am a software engineer and a Web developer. Always hungry to keep learning. # add description
social-twitter: cadlec_akpamoli
social-facebook: # add your Facebook handle
social-github: cadlec # add your Github handle
social-linkedin: cadlec-akpamoli
social-email: akpavite@gmail.com

# Disqus
discus-identifier: vitalakpamoli # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
